[package]
name = "jsonschema-python"
version = "0.16.2"
authors = ["Dmitry Dygalo <dadygalo@gmail.com>"]
edition = "2021"
license = "MIT"
readme = "README.rst"
description = "JSON schema validaton library"
repository = "https://github.com/Stranger6667/jsonschema-rs"
keywords = ["jsonschema", "validation"]
categories = ["web-programming"]
rust-version = "1.56.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "jsonschema_rs"
crate-type = ["cdylib"]

[build-dependencies]
built = { version = "0.5.2", features = ["chrono"] }

[dependencies.jsonschema]
path = "../../jsonschema"
version = "*"
default-features = false
features = ["resolve-http", "resolve-file"]

[dependencies]
serde_json = "1.0.91"
serde = "1.0.152"
pyo3 = { version = "0.17.3", features = ["extension-module"] }
pyo3-built = "0.4.7"

[package.metadata.maturin]
requires-python = ">=3.7"
project-url = { repository = "https://github.com/Stranger6667/jsonschema-rs" }
maintainer = "Dmitry Dygalo"
maintainer-email = "Dmitry Dygalo <dadygalo@gmail.com>"
classifier = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Rust",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
]

[profile.release]
codegen-units = 1
lto = "on"
